services:
  mongo:
    image: mongo:latest
    container_name: local-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-RadApple123!}
      MONGO_INITDB_DATABASE: homecoreos
    volumes:
      - mongo-data:/data/db
      - ./mongo-start.sh:/mongo-start.sh # Mount the script
    # Run the script with bash. 
    # This avoids 'chmod +x' issues on your host machine.
    command: ["bash", "/mongo-start.sh"]

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: homecoreos-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-RadApple123!}@mongo:27017/homecoreos?authSource=admin&replicaSet=rs0"
      HOSTNAME: "0.0.0.0"

  mongo-express:
    image: mongo-express
    container_name: local-mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-RadApple123!}
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASS:-BadOrange123!}

volumes:
  mongo-data: